name: Tauri Build & Release

on:
  push:
    tags:
      - 'v*.*.*'
      - 'test-*'

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node.js deps
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Install Tauri CLI
        run: cargo install tauri-cli --locked

      - name: Build app
        run: npm run tauri build

      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.3
        with:
          name: ${{ matrix.platform }}-bundle
          path: src-tauri/target/release/bundle/**/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows artifacts
        uses: actions/download-artifact@v3.1.3
        with:
          name: windows-latest-bundle
          path: ./release/windows

      - name: Download macOS artifacts
        uses: actions/download-artifact@v3.1.3
        with:
          name: macos-latest-bundle
          path: ./release/macos

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./release/windows/**/*.{msi,exe}
            ./release/macos/**/*.{dmg,zip}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
