name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Install Tauri CLI
        run: cargo install tauri-cli --locked

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-bundle
          path: src-tauri/target/release/bundle/**/*

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-latest-bundle
          path: ./release/windows

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: macos-latest-bundle
          path: ./release/macos

      - name: Create GitHub Release and upload binaries
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./release/windows/**/*.msi
            ./release/windows/**/*.exe
            ./release/macos/**/*.dmg
            ./release/macos/**/*.zip
            ./release/macos/**/*.app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
